<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.21" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BTG.Fondos.Auth\BTG.Fondos.Auth.csproj" />
    <ProjectReference Include="..\BTG.Fondos.BLL\BTG.Fondos.BLL.csproj" />
    <ProjectReference Include="..\BTG.Fondos.DTO\BTG.Fondos.DTO.csproj" />
  </ItemGroup>

</Project>
