<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BTG.Fondos.DAL\BTG.Fondos.DAL.csproj" />
    <ProjectReference Include="..\BTG.Fondos.DTO\BTG.Fondos.DTO.csproj" />
  </ItemGroup>

</Project>
